version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 3
  ignore:
      # The latest version of swagger at time of writing (3.0.0) is known to introduce breaking changes
      - dependency-name: "io.springfox:springfox-swagger2"
        versions: ["2.x", "3.x"]
      - dependency-name: "io.springfox:springfox-swagger-ui"
        versions: ["2.x", "3.x"]
      - dependency-name: "swaggerVersion"
        versions: ["2.x", "3.x"]
      # Version 4 of restAssured introduces breaking changes
      - dependency-name: "io.rest-assured:rest-assured"
        versions: ["4.x"]
        
