### Known breach for a known conviction and offender
GET http://{{host}}/offender/{{breach_crn}}/convictions/{{breach_convictionId}}/breaches/{{breach_breachId}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Breach for an unknown offender
GET http://{{host}}/offender/XX/convictions/{{breach_convictionId}}/breaches/{{breach_breachId}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Breach for an unknown conviction
GET http://{{host}}/offender/{{breach_crn}}/convictions/1234/breaches/{{breach_breachId}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Unknown breach
GET http://{{host}}/offender/{{breach_crn}}/convictions/{{breach_convictionId}}/breaches/1234

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}
