### 200, normal execution
GET http://{{host}}/offenders/{{offenderCrn}}/convictions/{{convictionId}}

### 404 - CRN not found
GET http://{{host}}/offenders/XX/convictions/{{convictionId}}

### 200 - empty attendances
GET http://{{host}}/offenders/{{offenderCrn}}/convictions/0

###
