### Known connvictions for a known offender
GET http://{{host}}/offenders/{{offenderCrn}}/convictions/{{convictionId}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Convictions for an unknown offender
GET http://{{host}}/offenders/XX/convictions/{{convictionId}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### 200 - empty attendances
GET http://{{host}}/offenders/{{offenderCrn}}/convictions/0

###
