# Create a case
PUT http://{{host}}/case/26081969
Content-Type: application/json

{
  "lastUpdated": "2019-12-14T09:00:00",
  "caseId": "26081969",
  "caseNo": "2608196900",
  "crn": "X111111",
  "pnc": "A/1234560BA",
  "listNo": "1st",
  "courtCode": "SHF",
  "courtRoom": "1",
  "sessionStartTime": "2020-01-13T09:00:00",
  "probationStatus": "Current",
  "previouslyKnownTerminationDate": null,
  "suspendedSentenceOrder": true,
  "breach": true,
  "offences": [],
  "defendantName": "Mr Christopher Faulkner Esq.",
  "defendantAddress": {
    "line1": "27",
    "line2": "Elm Place",
    "postcode": "ad21 5dr",
    "line3": "Bangor",
    "line4": null,
    "line5": null
  },
  "defendantSex": "M",
  "defendantDob": "1977-12-12",
  "nationality1": "British",
  "nationality2": null
}

###

# Update a case
PUT http://{{host}}/case/1168460
Content-Type: application/json

{
  "lastUpdated": "2019-12-14T09:00:00",
  "caseId": "1168460",
  "caseNo": "2608196900",
  "crn": "X320744",
  "pnc": "D/1234560BC",
  "listNo": "2nd",
  "courtCode": "SHF",
  "courtRoom": "1",
  "sessionStartTime": "2020-01-13T09:00:00",
  "probationStatus": "Current",
  "previouslyKnownTerminationDate": null,
  "suspendedSentenceOrder": true,
  "breach": true,
  "offences": [],
  "defendantName": "Mr Dylan Adam Armstrong",
  "defendantAddress": {
    "line1": "27",
    "line2": "Elm Place",
    "postcode": "ad21 5dr",
    "line3": "Bangor",
    "line4": null,
    "line5": null
  },
  "defendantSex": "M",
  "defendantDob": "1957-12-12",
  "nationality1": "British",
  "nationality2": null
}

### COURT AND CASE ENDPOINT
### Get by court and case
# Gives 200 because it's all known
GET http://{{host}}/court/SHF/case/1600028974
Accept: application/json

###
# Gives 404 because case no is unknown
GET http://{{host}}/court/SHF/case/0
Accept: application/json

###
# Gives 404 because court is unknown
http://{{host}}/court/SHF/case/0
Accept: application/json

###
### COURT AND CASE ENDPOINT
###

# No date - expect 400 bad request
GET http://{{host}}/court/SHF/cases
Accept: application/json

### Normal - 200
GET http://{{host}}/court/SHF/cases?date=2020-01-13
Accept: application/json

### Court not found expect 404
GET http://{{host}}/court/XXX/cases?date=2020-01-13
Accept: application/json

### Gets empty cases Normal - 200
GET http://{{host}}/court/SHF/cases?date=1903-01-13
Accept: application/json

###

