# Create a case
PUT http://{{host}}/case/26081969
Content-Type: application/json

{
  "lastUpdated": "2019-12-14T09:00:00",
  "caseId": "26081969",
  "caseNo": "2608196900",
  "crn": "X111111",
  "courtCode": "SHF",
  "courtRoom": "1",
  "sessionStartTime": "2020-01-13T09:00:00",
  "probationStatus": "Current",
  "previouslyKnownTerminationDate": null,
  "suspendedSentenceOrder": true,
  "breach": true,
  "data": "{\"inf\": \"POL01\", \"c_id\": 1168463, \"cseq\": 1, \"h_id\": 1246257, \"type\": \"C\", \"valid\": \"Y\", \"caseno\": 1600028974, \"listno\": \"1st\", \"def_age\": 29, \"def_dob\": \"02/08/1990\", \"def_sex\": \"N\", \"def_addr\": {\"line1\": \"line1\", \"line2\": \"line2\", \"line3\": \"line3\", \"pcode\": \"S1 6ua\"}, \"def_name\": \"Mr Dylan Adam Armstrong\", \"def_type\": \"P\", \"offences\": {\"offence\": {\"as\": \"Contrary to section 363(2) and (4) of the Communications Act 2003.\", \"sof\": \".\", \"sum\": \"On 05/09/2016 used a colour television receiver without a licence at the above address.\", \"code\": \"CA03010\", \"oseq\": 1, \"co_id\": 1142431, \"title\": \"Use a television set without a licence\", \"maxpen\": \"S: L3\"}}}",
  "offences": [],
  "defendantName": "Mr Christopher Faulkner Esq.",
  "defendantAddress": {
    "line1": "27",
    "line2": "Elm Place",
    "postcode": "ad21 5dr",
    "line3": "Bangor",
    "line4": null,
    "line5": null
  }
}

###

# Update a case
PUT http://{{host}}/case/1168460
Content-Type: application/json

{
  "lastUpdated": "2019-12-14T09:00:00",
  "caseId": "1168460",
  "caseNo": "2608196900",
  "crn": "X320744",
  "courtCode": "SHF",
  "courtRoom": "1",
  "sessionStartTime": "2020-01-13T09:00:00",
  "probationStatus": "Current",
  "previouslyKnownTerminationDate": null,
  "suspendedSentenceOrder": true,
  "breach": true,
  "data": "{\"inf\": \"POL01\", \"c_id\": 1168463, \"cseq\": 1, \"h_id\": 1246257, \"type\": \"C\", \"valid\": \"Y\", \"caseno\": 1600028974, \"listno\": \"1st\", \"def_age\": 29, \"def_dob\": \"02/08/1990\", \"def_sex\": \"N\", \"def_addr\": {\"line1\": \"line1\", \"line2\": \"line2\", \"line3\": \"line3\", \"pcode\": \"S1 6ua\"}, \"def_name\": \"Mr Dylan Adam Armstrong\", \"def_type\": \"P\", \"offences\": {\"offence\": {\"as\": \"Contrary to section 363(2) and (4) of the Communications Act 2003.\", \"sof\": \".\", \"sum\": \"On 05/09/2016 used a colour television receiver without a licence at the above address.\", \"code\": \"CA03010\", \"oseq\": 1, \"co_id\": 1142431, \"title\": \"Use a television set without a licence\", \"maxpen\": \"S: L3\"}}}",
  "offences": [],
  "defendantName": "Mr Dylan Adam Armstrong",
  "defendantAddress": {
    "line1": "27",
    "line2": "Elm Place",
    "postcode": "ad21 5dr",
    "line3": "Bangor",
    "line4": null,
    "line5": null
  }
}

### COURT AND CASE ENDPOINT
### Get by court and case
# Gives 200 because it's all known
GET http://{{host}}/court/SHF/case/1600028974
Accept: application/json

###
# Gives 404 because case no is unknown
GET http://{{host}}/court/SHF/case/0
Accept: application/json

###
# Gives 404 because court is unknown
http://{{host}}/court/SHF/case/0
Accept: application/json

###
### COURT AND CASE ENDPOINT
###

# No date - expect 400 bad request
GET http://{{host}}/court/SHF/cases
Accept: application/json

### Normal - 200
GET http://{{host}}/court/SHF/cases?date=2020-01-13
Accept: application/json

### Court not found expect 404
GET http://{{host}}/court/XXX/cases?date=2020-01-13
Accept: application/json

### Gets empty cases Normal - 200
GET http://{{host}}/court/SHF/cases?date=1903-01-13
Accept: application/json

###

