### 200, normal execution
GET http://{{host}}/offender/{{offenderCrn}}/probation-record

### 404 - CRN not found
GET http://{{host}}/offender/XX/probation-record

### 200 - normal execution
GET http://{{host}}/offender/{{offenderCrn}}/convictions/{{convictionId}}/requirements

### 404 - CRN not found
GET http://{{host}}/offender/XXXX/convictions/{{convictionId}}/requirements

### 200 but empty requirements
GET http://{{host}}/offender/{{offenderCrn}}/convictions/0/requirements

###
