community-api:
  base-url: https://community-api-secure.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

offender-assessments-api:
  base-url: https://dev.devtest.assessment-api.hmpps.dsd.io

delius:
  base-url: https://ndelius.test.probation.service.justice.gov.uk

prison-api:
  base-url: https://prison-api-dev.prison.service.justice.gov.uk

manage-offences-api:
  base-url: https://manage-offences-api-dev.hmpps.service.justice.gov.uk

court-case-and-delius-api:
  base-url: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

domain-event-and-delius-api:
  base-url: https://domain-events-and-delius-dev.hmpps.service.justice.gov.uk

hmpps-document-management-api-client:
  base-url: https://document-api-dev.hmpps.service.justice.gov.uk

feature:
  flags:
    use-community-api-for-probation-status: true

hearing_outcomes:
  move_un_resulted_to_outcomes_cutoff_time: "12:00"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${nomis-oauth.base-url}/auth/.well-known/jwks.json