community-api:
  base-url: https://community-api-secure.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://gateway.t3.nomis-api.hmpps.dsd.io

offender-assessments-api:
  base-url: https://offender-preprod.aks-live-1.studio-hosting.service.hmpps.dsd.io
