community-api:
  base-url: https://community-api-secure.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

offender-assessments-api:
  base-url: https://dev.devtest.assessment-api.hmpps.dsd.io

delius:
  base-url: https://ndelius.test.probation.service.justice.gov.uk

prison-api:
  base-url: https://api-dev.prison.service.justice.gov.uk
  
feature:
  flags:
    use-community-api-for-probation-status: true
