{{- if .Values.data_dictionary -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.data_dictionary.name }}
  labels:
    app: {{ .Values.data_dictionary.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.data_dictionary.service.port.http }}
      targetPort: {{ .Values.data_dictionary.deployment.port }}
      protocol: TCP
      name: {{ .Values.data_dictionary.name }}-http
  selector:
    app: {{ .Values.data_dictionary.name }}

{{- end }}