apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: court-case-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /ping
              port: {{ .Values.image.port }}
            initialDelaySeconds: 60
            failureThreshold: 360
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.image.port }}
            periodSeconds: 30
            initialDelaySeconds: 90
            timeoutSeconds: 20
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.image.port }}
            periodSeconds: 20
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 15
        {{ if .Values.resources }}
          resources:
            limits:
              cpu: {{ .Values.resources.cpu.limit }}
              memory: {{ .Values.resources.memory.limit }}
            requests:
              cpu: {{ .Values.resources.cpu.request}}
              memory: {{ .Values.resources.memory.request }}
        {{ end }}
{{ include "deployment.envs" . | nindent 10 }}
