apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx_proxy.name }}
  labels:
    app: {{ .Values.nginx_proxy.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  securityContext:
    capabilities:
      add:
        - NET_BIND_SERVICE
  ports:
    - port: {{ .Values.nginx_proxy.service.port.http }}
      targetPort: {{ .Values.nginx_proxy.deployment.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nginx_proxy.name }}
