apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}-process-un-resulted-cases-cronjob
spec:
  schedule: {{ .Values.hearing_outcomes.process_un_resulted_cases_cron }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPUT http://{{ template "app.fullname" . }}/process-un-resulted-cases
          restartPolicy: Never
