---
{{ if .Values.takeDatabaseSnapshots }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: court-case-service-db-snapshot-job
    prometheus: cloud-platform
  name: court-case-service-prometheus-rules-db-snapshot
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: DB-rds-snapshot-job-failed
      annotations:
        message: Database snapshot job for { .Release.Namespace }}/{{ .Release.Name }} failed to complete.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
      expr: max((kube_job_status_failed{job_name=~"rds-snapshot-job.*",namespace="{{ .Release.Namespace }}"} > 0) + ((time() - kube_job_status_start_time{job_name=~"rds-snapshot-job.*",namespace="{{ .Release.Namespace }}"}) < 60 * 10)) by (job_name,namespace)
      for: 1m
      labels:
        severity: court-case-service
{{ end }}

