apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}-retry-dlq-cronjob
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPUT http://{{ template "app.fullname" . }}/queue-admin/retry-all-dlqs
          restartPolicy: Never
