INSERT INTO court (name, court_code, version, created, last_updated, deleted, created_by)
    VALUES
        ('Cirencester Magistrates'' Court', 'B53DT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Central Criminal Court', 'C01CE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Nottingham Crown Court', 'C31NT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Maidstone Magistrates'' Court', 'B46IR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newcastle Magistrates'' Court', 'B10JL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lincoln Crown Court', 'C32LI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Shrewsbury Crown Court', 'C22SW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chelmsford Magistrates'' Court', 'B42CM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Barkingside Magistrates'' Court', 'B01KR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Worcester Magistrates'' Court', 'B22OS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('St George''s Hall', 'B05GP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Norwich Crown Court', 'C36NR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Highbury Corner Magistrates'' Court', 'B01GU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Derby Crown Court', 'C30DE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lewes Crown Court', 'C47LW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Ealing Magistrates'' Court', 'B01FA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wimbledon Magistrates'' Court', 'B01OK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cardiff Magistrates'' Court', 'B62DC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Nuneaton Magistrates'' Court', 'B23PP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Swindon Magistrates'' Court', 'B54MW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cambridge Crown Court', 'C35CM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Camberwell Green Magistrates'' Court', 'B01CX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Uxbridge Magistrates'' Court', 'B01NM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Doncaster Magistrates'' Court', 'B14ET', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Peterborough Magistrates'' Court', 'B35KE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Taunton Magistrates'' Court', 'B52MY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Westminster Magistrates'' Court', 'B01IX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Boston Magistrates'' Court', 'B32BX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Coventry Crown Court', 'C20CO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Croydon Magistrates'' Court', 'B01EF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Salisbury Crown Court', 'C54SL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Barnstaple Magistrates'' Court', 'B50AW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Romford Magistrates'' Court', 'B01LA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Coventry Magistrates'' Court', 'B20EB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Folkestone Magistrates'' Court', 'B46FO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Welshpool Magistrates'' Court', 'B63NZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Sheffield Crown Court', 'C14SH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Southwark Crown Court', 'C01SW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Southampton Crown Court', 'C44SA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Mansfield Magistrates'' Court', 'B31IT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bath Magistrates'' Court', 'B52BB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Kidderminster Magistrates'' Court', 'B22HM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Llandrindod Wells Magistrates'' Court', 'B63IC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bournemouth Crown Court', 'C55BN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wellingborough Magistrates'' Court', 'B34NX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Reading Magistrates'' Court', 'B43KQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Northallerton Magistrates'' Court', 'B12JR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Caernarfon Crown Court', 'C07CA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cardiff Crown Court', 'C62CR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chesterfield Magistrates'' Court', 'B30PG', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Thames Magistrates'' Court', 'B01ND', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Guildford Magistrates'' Court', 'B45GC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Guildford Crown Court', 'C45GU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Dudley Magistrates'' Court', 'B20EY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newport (South Wales) Crown Court', 'C62NG', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Peterlee Magistrates'' Court', 'B11KF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Croydon Crown Court', 'C01CY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('York Crown Court', 'C12YO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Slough Courthouse', 'B43LV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Winchester Crown Court', 'C44WI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Staines Magistrates'' Court', 'B45MH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Llandudno Magistrates'' Court', 'B60ID', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Leicester Crown Court', 'C33LC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Isleworth Crown Court', 'C01IS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Milton Keynes Magistrates'' Court', 'B43JC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Harrogate Magistrates'' Court', 'B12GH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bromley Magistrates'' Court', 'B01CN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Burnley Crown Court', 'C04BU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Scarborough Magistrates'' Court', 'B12LK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Stratford Magistrates'' Court', 'B01MN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Derby Justice Centre (aka Derby St Mary Adult)', 'B30PI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Sevenoaks Magistrates'' Court', 'B46LN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bodmin Magistrates'' Court', 'B50BU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bristol Crown Court', 'C52BT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Luton Magistrates'' Court', 'B40IM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('City of London Magistrates'' Court', 'B01DU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Northampton Crown Court', 'C34NO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Willesden Magistrates'' Court', 'B01CE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Hendon Magistrates'' Court', 'B01GQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bradford Crown Court', 'C13BR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Teesside Crown Court', 'C17TE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Colchester Magistrates'' Court', 'B42CO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Blackfriars Crown Court', 'C01BL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Snaresbrook Crown Court', 'C01SN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Hull Magistrates'' Court', 'B16HE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Llanelli Magistrates'' Court', 'B63IE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Preston Crown Court', 'C04PR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wolverhampton Crown Court', 'C20WO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cwmbran Magistrates'' Court', 'B61EH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Amersham Magistrates'' Court', 'B43AJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Maidenhead Courthouse', 'B43IQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newport (I.O.W.) Crown Court', 'C44NI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wirral Magistrates'' Court', 'B05BK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bristol Magistrates'' Court', 'B52CM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Poole Magistrates'' Court', 'B55KL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Carlisle Magistrates'' Court', 'B03DE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newcastle upon Tyne Magistrates'' Court', 'B10JJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Telford Magistrates'' Court', 'B22MZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chester Crown Court', 'C07CS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Southend Crown Court', 'C42SE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('St. Albans Crown Court', 'C41ST', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Shrewsbury Crown Court', 'C22SR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Swansea Crown Court', 'C62SS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wolverhampton Magistrates'' Court', 'B20OQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Plymouth Magistrates'' Court', 'B50KH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Birmingham Crown Court', 'C20BI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Ipswich Crown Court', 'C37IP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cheltenham Magistrates'' Court', 'B53DJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Kingston upon Thames Crown Court', 'C01KT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Durham Crown Court', 'C11DU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Beverley Magistrates'' Court', 'B16BG', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Manchester Crown Court', 'C06MC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newport Magistrates'' Court', 'B61NP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Peterborough Crown Court', 'C35PE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Barrow-in-Furness Magistrates'' Court', 'B03AX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Leeds Crown Court', 'C13LE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Banbury Magistrates'' Court', 'B43AQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chelmsford Crown Court', 'C42CF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Exeter Crown Court', 'C50EX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wood Green Crown Court', 'C01WG', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Blackburn Magistrates'' Court', 'B04BP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Swansea Magistrates'' Court', 'B62MV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Workington Magistrates'' Court', 'B03OT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Birmingham Magistrates'' Court', 'B20BL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bradford Magistrates'' Court', 'B13CC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Doncaster Crown Court', 'C14DN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Warrington Crown Court', 'C07WA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Hereford Crown Court', 'C22HE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cambridge Magistrates'' Court', 'B35CZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Woolwich Crown Court', 'C01WL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wigan Magistrates'' Court', 'B06OJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Hastings Magistrates'' Court', 'B47GL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Canterbury Magistrates'' Court', 'B46DB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Exeter Magistrates'' Court', 'B50FI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Crewe Magistrates'' Court', 'B07ED', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Redditch Magistrates'' Court', 'B22KS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Minshull Street Manchester Crown Court', 'C06MM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Basildon Crown Court', 'C42BS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Skipton Magistrates'' Court', 'B12LT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wrexham Magistrates'' Court', 'B60OW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Taunton Crown Court', 'C52TA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Stockport Magistrates'' Court', 'B06MK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Nottingham Magistrates'' Court', 'B31JV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bridlington Magistrates'' Court', 'B16CJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Aberystwyth Magistrates'' Court', 'B63AD', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Inner London Crown Court', 'C01IL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Carlisle Crown Court', 'C03CL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Preston Magistrates'' Court', 'B04KO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Blackpool Magistrates'' Court', 'B04BQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Plymouth Crown Court', 'C50PL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Caernarfon Magistrates'' Court', 'B60WU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Cannock Magistrates'' Court', 'B21DA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Stafford Crown Court', 'C21SF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Liverpool Crown Court', 'C05LV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('York Magistrates'' Court', 'B12PA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('St. Albans Magistrates'' Court', 'B41ME', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Stevenage Magistrates'' Court', 'B41MJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Reading Crown Court', 'C43RE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Mold Magistrates'' Court', 'B60JE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Northampton Magistrates'' Court', 'B34JS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Basildon Magistrates'' Court', 'B42AZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bolton Combined Court Centre', 'B06BV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Gloucester Crown Court', 'C53GL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Great Grimsby Crown Court', 'C16GR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Leeds Magistrates'' Court', 'B13HT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Manchester City Magistrates'' Court', 'B06IS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newcastle upon Tyne Crown Court', 'C10NE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Harrow Crown Court', 'C01HA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Warwick Crown Court sitting at Leamington Spa', 'C23WR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Southend-on-Sea Magistrates'' Court', 'B42MB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Huntingdon Magistrates'' Court', 'B35HF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Grimsby Magistrates'' Court', 'B16GB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Haverfordwest Magistrates'' Court', 'B63GN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Huddersfield Magistrates'' Court', 'B13HD', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Herefordshire Magistrates'' Court', 'B22GR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('South Shields Magistrates'' Court', 'B10LX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Luton Crown Court', 'C40LU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Worcester Crown Court', 'C22WC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Ipswich Magistrates'' Court', 'B37HI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newton Aycliffe Magistrates'' Court', 'B11JP', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Stoke-on-Trent Crown Court', 'C21SK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Norwich Magistrates'' Court', 'B36JU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lincoln Magistrates'' Court', 'B32HX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lancaster Crown Court', 'C04LA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Sheffield Magistrates'' Court', 'B14LO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Horsham Magistrates'' Court', 'B47HB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Walsall Magistrates'' Court', 'B20NQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Barnsley Magistrates'' Court', 'B14AV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Leicester Magistrates'' Court', 'B33HU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Great Yarmouth Magistrates'' Court', 'B36FZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Berwick-upon-Tweed Magistrates'' Court', 'B10BF', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Mold Crown Court', 'C07MO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Liverpool Magistrates'' Court', 'B05PK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Burnley Magistrates'' Court', 'B04CO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Medway Magistrates'' Court', 'B46DH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('North Somerset Magistrates'' Court', 'B52OC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Aldershot Magistrates'' Court', 'B44AG', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('King''s Lynn Crown Court', 'C36KL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Teesside Magistrates'' Court', 'B17JA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Isle of Wight Magistrates'' Court', 'B44JK', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Eastbourne Magistrates'' Court', 'B47FB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('North Shields Magistrates'' Court', 'B10JQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Tameside Magistrates'' Court', 'B06AN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Wycombe Magistrates'' Court', 'B43OX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newport Magistrates'' Court (Crown Court Bldg)', 'B61WY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bedford Magistrates'' Court', 'B40BC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chester Magistrates'' Court', 'B07DM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Winchester Combined Court', 'B44WZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Warrington Combined Court', 'B07FQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bournemouth Combined Court', 'B55IS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('West Norfolk Magistrates'' Court', 'B36HN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('South East Northumberland Magistrates'' Court (aka Bedlington MC)', 'B10BD', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Darlington Magistrates'' Court', 'B11EI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bexley Magistrates'' Court', 'B01BH', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Merthyr Tydfil Magistrates'' Court', 'B62IZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Loughborough Magistrates'' Court', 'B33II', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chichester Crown Court', 'C47CC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Chorley Magistrates'' Court', 'B04DS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Gateshead Magistrates'' Court', 'B10FR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Salisbury Magistrates'' Court', 'B54WV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('North Staffordshire Justice Centre', 'B21JI', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Hatfield Magistrates'' Court', 'B41US', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Leamington Spa Magistrates'' Court', 'B23HS', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lancaster Magistrates'' Court', 'B04HQ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Lavender Hill Magistrates'' Court', 'B01LY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Bolton Crown Court', 'C06BO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Kingston-upon-Hull Crown Court', 'C16HU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('South Sefton Magistrates'' Court', 'B05BW', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Sunderland Magistrates'' Court', 'B10MR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Yeovil Magistrates'' Court', 'B52OZ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Newton Abbot Magistrates'' Court', 'B50JO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Brighton Magistrates'' Court', 'B47CL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Margate Magistrates'' Court', 'B46IU', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('West Hampshire Magistrates'' Court', 'B44MA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Portsmouth Magistrates'' Court', 'B44KM', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Basingstoke Magistrates'' Court', 'B44BA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Swindon Crown Court', 'C54SD', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Truro Crown Court', 'C50TR', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Crawley Magistrates'' Court', 'B47EC', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Oxford Magistrates'' Court', 'B43KB', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Aylesbury Crown Court', 'C43AY', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Court of Appeal', 'C01CJ', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Worthing Magistrates'' Court', 'B47OV', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Canterbury Crown Court', 'C46CN', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Portsmouth Crown Court', 'C44PO', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Truro Magistrates'' Court', 'B50NL', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Maidstone Crown Court', 'C46MA', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Merthyr Tydfil Crown Court', 'C62MT', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Weymouth Magistrates'' Court', 'B55OE', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql'),
        ('Oxford Crown Court', 'C43OX', 0, NOW(), NOW(), false, 'R__add_all_crown_court_names.sql')
    ON CONFLICT (COURT_CODE)
    DO
        UPDATE SET name = EXCLUDED.name,
            version = court.version + 1,
            created = court.created,
            last_updated=NOW();