ALTER TABLE COURT_CASE DROP COLUMN DATA;
ALTER TABLE COURT_CASE ADD COLUMN PNC TEXT;
ALTER TABLE COURT_CASE ADD COLUMN LIST_NO TEXT;
ALTER TABLE COURT_CASE ADD COLUMN DEFENDANT_DOB DATE;
ALTER TABLE COURT_CASE ADD COLUMN DEFENDANT_SEX TEXT;
ALTER TABLE COURT_CASE ADD COLUMN NATIONALITY_1 TEXT;
ALTER TABLE COURT_CASE ADD COLUMN NATIONALITY_2 TEXT;
