BEGIN;
create table offender_match (id int8 generated by default as identity, confirmed boolean not null, crn varchar(255) not null, cro varchar(255), match_type varchar(255) not null, pnc varchar(255), group_id int8 not null, primary key (id));
create table offender_match_group (id int8 generated by default as identity, case_no varchar(255) not null, court_code varchar(255) not null, primary key (id));

alter table if exists offender_match add constraint fk_offender_match_group foreign key (group_id) references offender_match_group;
alter table if exists offender_match_group add constraint fk_offender_match_group_court_case foreign key (case_no, court_code) references court_case (case_no, court_code);

COMMIT;