BEGIN;

create table immutable_offence
(
    id              int8 generated by default as identity,
    created         timestamp not null,
    created_by      varchar(255),
    deleted         boolean   not null,
    version         int4      not null,
    act             varchar(255),
    offence_summary varchar(255),
    offence_title   varchar(255),
    sequence_number int4      not null,
    court_case_id   int8,
    primary key (id)
);

alter table if exists immutable_offence add constraint fk_offence_court_case_id
    foreign key (court_case_id) references court_case;

ALTER TABLE offence DROP CONSTRAINT fk_offence_court_case;
ALTER TABLE offender_match_group DROP CONSTRAINT fk_offender_match_group_court_case;
ALTER TABLE court_case DROP CONSTRAINT court_case_uq;

INSERT INTO immutable_offence (created, created_by, deleted, version, act, offence_summary, offence_title,
                               sequence_number, court_case_id)
SELECT o.created,o.created_by,o.deleted,1,o.act,o.offence_summary,o.offence_title,o.sequence_number,c.id
    FROM offence o
             JOIN court_case c
                  ON o.court_code = c.court_code AND o.case_no = c.case_no;

COMMIT;
