BEGIN;
create table offender_match (id int8 generated by default as identity, case_no varchar(255) not null, confirmed boolean not null, court_code varchar(255) not null, crn varchar(255) not null, cro varchar(255), match_type varchar(255), pnc varchar(255), primary key (id));
create table offender_match_group (id int8 generated by default as identity, case_no varchar(255) not null, court_code varchar(255) not null, primary key (id));
create table offender_match_group_offender_matches (grouped_offender_matches_entity_id int8 not null, offender_matches_id int8 not null);

alter table if exists offender_match_group_offender_matches add constraint uq_offender_match_group_offender_matches_id unique (offender_matches_id);
alter table if exists offender_match add constraint fk_offender_match_court_code_case_no foreign key (case_no, court_code) references court_case (case_no, court_code);
alter table if exists offender_match_group add constraint fk_offender_match_group_court_code_case_no foreign key (case_no, court_code) references court_case (case_no, court_code);
alter table if exists offender_match_group_offender_matches add constraint fk_offender_match_group_offender_matches_offender_match foreign key (offender_matches_id) references offender_match;
alter table if exists offender_match_group_offender_matches add constraint fk_offender_match_group_offender_grouped_matches foreign key (grouped_offender_matches_entity_id) references offender_match_group;
COMMIT;