BEGIN;

CREATE TABLE court_case_bk AS TABLE court_case;
CREATE TABLE offence_bk AS TABLE offence;

create table immutable_offence
(
    id              int8 generated by default as identity,
    created         timestamp not null default now(),
    created_by              text            null,
    act                     text            null,
    offence_summary         text            null,
    offence_title           text            null,
    sequence_number int4      not null,
    court_case_id   int8 not null,
    primary key (id),
    CONSTRAINT fk_immutable_offence_court_case FOREIGN KEY (court_case_id) REFERENCES COURT_CASE (ID)
);

alter table if exists immutable_offence add constraint fk_offence_court_case_id
    foreign key (court_case_id) references court_case;

ALTER TABLE offence DROP CONSTRAINT fk_offence_court_case;
ALTER TABLE offender_match_group DROP CONSTRAINT fk_offender_match_group_court_case;
ALTER TABLE court_case DROP CONSTRAINT court_case_uq;
ALTER TABLE court_case DROP COLUMN version;

INSERT INTO immutable_offence (created, created_by, act, offence_summary, offence_title,
                               sequence_number, court_case_id)
SELECT o.created,o.created_by,o.act,o.offence_summary,o.offence_title,o.sequence_number,c.id
    FROM offence o
             JOIN court_case c
                  ON o.court_code = c.court_code AND o.case_no = c.case_no;

DROP TABLE offence;
ALTER TABLE immutable_offence RENAME TO offence;

COMMIT;
