create table immutable_offence
(
    id              int8 generated by default as identity,
    created         timestamp not null,
    created_by      varchar(255),
    deleted         boolean   not null,
    version         int4      not null,
    act             varchar(255),
    offence_summary varchar(255),
    offence_title   varchar(255),
    sequence_number int4      not null,
    court_case_id   int8,
    primary key (id)
);

alter table if exists immutable_offence add constraint FKhb0700edl219o5qjfu7hved8k
    foreign key (court_case_id) references court_case;