BEGIN;
    ALTER TABLE DEFENDANT ADD COLUMN PROBATION_STATUS TEXT;
    ALTER TABLE DEFENDANT ADD COLUMN SUSPENDED_SENTENCE_ORDER BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE DEFENDANT ADD COLUMN BREACH BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE DEFENDANT ADD COLUMN PRE_SENTENCE_ACTIVITY BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE DEFENDANT ADD COLUMN PREVIOUSLY_KNOWN_TERMINATION_DATE DATE;
    ALTER TABLE DEFENDANT ADD COLUMN AWAITING_PSR BOOLEAN;
    ALTER TABLE DEFENDANT ADD COLUMN MANUAL_UPDATE BOOLEAN NOT NULL DEFAULT FALSE;

    UPDATE DEFENDANT SET SUSPENDED_SENTENCE_ORDER = false;
    UPDATE DEFENDANT SET manual_update = false;
    UPDATE DEFENDANT SET BREACH = false;
    UPDATE DEFENDANT SET PRE_SENTENCE_ACTIVITY = false;

    UPDATE DEFENDANT SET manual_update = true where CREATED_BY LIKE '%(prepare-a-case-for-court)';

COMMIT;
