BEGIN;

UPDATE DEFENDANT SET SEX = 'MALE' WHERE SEX = 'M';
UPDATE DEFENDANT SET SEX = 'FEMALE' WHERE SEX = 'F';
UPDATE DEFENDANT SET SEX = 'NOT_KNOWN' WHERE SEX = 'N';
UPDATE DEFENDANT SET SEX = 'NOT_KNOWN' WHERE SEX is null;
-- CP will always send a value and we will default NULLS to NOT_KNOWN
ALTER TABLE DEFENDANT ALTER COLUMN SEX SET NOT NULL;

-- This field will be retired soon but adding for completeness
UPDATE COURT_CASE SET DEFENDANT_SEX = 'MALE' WHERE DEFENDANT_SEX = 'M';
UPDATE COURT_CASE SET DEFENDANT_SEX = 'FEMALE' WHERE DEFENDANT_SEX = 'F';
UPDATE COURT_CASE SET DEFENDANT_SEX = 'NOT_KNOWN' WHERE DEFENDANT_SEX = 'N';
UPDATE COURT_CASE SET DEFENDANT_SEX = 'NOT_KNOWN' WHERE DEFENDANT_SEX is null;

COMMIT;
