BEGIN;

UPDATE DEFENDANT SET SEX = 'MALE' WHERE SEX = 'M';
UPDATE DEFENDANT SET SEX = 'FEMALE' WHERE SEX = 'F';
UPDATE DEFENDANT SET SEX = 'NOT_KNOWN' WHERE SEX = 'N';

UPDATE COURT_CASE SET DEFENDANT_SEX = 'MALE' WHERE DEFENDANT_SEX = 'M';
UPDATE COURT_CASE SET DEFENDANT_SEX = 'FEMALE' WHERE DEFENDANT_SEX = 'F';
UPDATE COURT_CASE SET DEFENDANT_SEX = 'NOT_KNOWN' WHERE DEFENDANT_SEX = 'N';

COMMIT;
