BEGIN;

CREATE TABLE PIC_2018_HEARING_BK AS
  TABLE HEARING;

ALTER TABLE HEARING
    RENAME TO HEARING_DAY;

CREATE TABLE PIC_2018_COURT_CASE_BK AS
  TABLE COURT_CASE;

ALTER TABLE COURT_CASE
    DROP COLUMN manual_update;

COMMIT;
