INSERT INTO court (name, court_code, version, created, last_updated, deleted, created_by)
    VALUES
        ('Cirencester Magistrates'' Court', 'B53DT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Central Criminal Court', 'C01CE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Nottingham Crown Court', 'C31NT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Maidstone Magistrates'' Court', 'B46IR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newcastle Magistrates'' Court', 'B10JL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lincoln Crown Court', 'C32LI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Shrewsbury Crown Court', 'C22SW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chelmsford Magistrates'' Court', 'B42CM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Barkingside Magistrates'' Court', 'B01KR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Worcester Magistrates'' Court', 'B22OS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('St George''s Hall', 'B05GP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Norwich Crown Court', 'C36NR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Highbury Corner Magistrates'' Court', 'B01GU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Derby Crown Court', 'C30DE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lewes Crown Court', 'C47LW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Ealing Magistrates'' Court', 'B01FA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wimbledon Magistrates'' Court', 'B01OK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cardiff Magistrates'' Court', 'B62DC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Nuneaton Magistrates'' Court', 'B23PP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Swindon Magistrates'' Court', 'B54MW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cambridge Crown Court', 'C35CM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Camberwell Green Magistrates'' Court', 'B01CX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Uxbridge Magistrates'' Court', 'B01NM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Doncaster Magistrates'' Court', 'B14ET00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Peterborough Magistrates'' Court', 'B35KE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Taunton Magistrates'' Court', 'B52MY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Westminster Magistrates'' Court', 'B01IX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Boston Magistrates'' Court', 'B32BX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Coventry Crown Court', 'C20CO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Croydon Magistrates'' Court', 'B01EF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Salisbury Crown Court', 'C54SL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Barnstaple Magistrates'' Court', 'B50AW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Romford Magistrates'' Court', 'B01LA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Coventry Magistrates'' Court', 'B20EB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Folkestone Magistrates'' Court', 'B46FO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Welshpool Magistrates'' Court', 'B63NZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Sheffield Crown Court', 'C14SH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Southwark Crown Court', 'C01SW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Southampton Crown Court', 'C44SA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Mansfield Magistrates'' Court', 'B31IT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bath Magistrates'' Court', 'B52BB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Kidderminster Magistrates'' Court', 'B22HM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Llandrindod Wells Magistrates'' Court', 'B63IC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bournemouth Crown Court', 'C55BN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wellingborough Magistrates'' Court', 'B34NX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Reading Magistrates'' Court', 'B43KQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Northallerton Magistrates'' Court', 'B12JR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Caernarfon Crown Court', 'C07CA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cardiff Crown Court', 'C62CR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chesterfield Magistrates'' Court', 'B30PG00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Thames Magistrates'' Court', 'B01ND00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Guildford Magistrates'' Court', 'B45GC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Guildford Crown Court', 'C45GU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Dudley Magistrates'' Court', 'B20EY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newport (South Wales) Crown Court', 'C62NG00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Peterlee Magistrates'' Court', 'B11KF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Croydon Crown Court', 'C01CY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('York Crown Court', 'C12YO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Slough Courthouse', 'B43LV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Winchester Crown Court', 'C44WI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Staines Magistrates'' Court', 'B45MH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Llandudno Magistrates'' Court', 'B60ID00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Leicester Crown Court', 'C33LC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Isleworth Crown Court', 'C01IS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Milton Keynes Magistrates'' Court', 'B43JC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Harrogate Magistrates'' Court', 'B12GH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bromley Magistrates'' Court', 'B01CN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Burnley Crown Court', 'C04BU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Scarborough Magistrates'' Court', 'B12LK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Stratford Magistrates'' Court', 'B01MN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Derby Justice Centre (aka Derby St Mary Adult)', 'B30PI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Sevenoaks Magistrates'' Court', 'B46LN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bodmin Magistrates'' Court', 'B50BU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bristol Crown Court', 'C52BT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Luton Magistrates'' Court', 'B40IM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('City of London Magistrates'' Court', 'B01DU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Northampton Crown Court', 'C34NO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Willesden Magistrates'' Court', 'B01CE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Hendon Magistrates'' Court', 'B01GQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bradford Crown Court', 'C13BR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Teesside Crown Court', 'C17TE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Colchester Magistrates'' Court', 'B42CO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Blackfriars Crown Court', 'C01BL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Snaresbrook Crown Court', 'C01SN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Hull Magistrates'' Court', 'B16HE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Llanelli Magistrates'' Court', 'B63IE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Preston Crown Court', 'C04PR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wolverhampton Crown Court', 'C20WO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cwmbran Magistrates'' Court', 'B61EH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Amersham Magistrates'' Court', 'B43AJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Maidenhead Courthouse', 'B43IQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newport (I.O.W.) Crown Court', 'C44NI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wirral Magistrates'' Court', 'B05BK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bristol Magistrates'' Court', 'B52CM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Poole Magistrates'' Court', 'B55KL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Carlisle Magistrates'' Court', 'B03DE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newcastle upon Tyne Magistrates'' Court', 'B10JJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Telford Magistrates'' Court', 'B22MZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chester Crown Court', 'C07CS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Southend Crown Court', 'C42SE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('St. Albans Crown Court', 'C41ST00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Shrewsbury Crown Court', 'C22SR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Swansea Crown Court', 'C62SS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wolverhampton Magistrates'' Court', 'B20OQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Plymouth Magistrates'' Court', 'B50KH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Birmingham Crown Court', 'C20BI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Ipswich Crown Court', 'C37IP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cheltenham Magistrates'' Court', 'B53DJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Kingston upon Thames Crown Court', 'C01KT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Durham Crown Court', 'C11DU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Beverley Magistrates'' Court', 'B16BG00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Manchester Crown Court', 'C06MC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newport Magistrates'' Court', 'B61NP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Peterborough Crown Court', 'C35PE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Barrow-in-Furness Magistrates'' Court', 'B03AX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Leeds Crown Court', 'C13LE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Banbury Magistrates'' Court', 'B43AQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chelmsford Crown Court', 'C42CF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Exeter Crown Court', 'C50EX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wood Green Crown Court', 'C01WG00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Blackburn Magistrates'' Court', 'B04BP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Swansea Magistrates'' Court', 'B62MV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Workington Magistrates'' Court', 'B03OT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Birmingham Magistrates'' Court', 'B20BL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bradford Magistrates'' Court', 'B13CC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Doncaster Crown Court', 'C14DN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Warrington Crown Court', 'C07WA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Hereford Crown Court', 'C22HE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cambridge Magistrates'' Court', 'B35CZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Woolwich Crown Court', 'C01WL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wigan Magistrates'' Court', 'B06OJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Hastings Magistrates'' Court', 'B47GL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Canterbury Magistrates'' Court', 'B46DB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Exeter Magistrates'' Court', 'B50FI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Crewe Magistrates'' Court', 'B07ED00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Redditch Magistrates'' Court', 'B22KS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Minshull Street Manchester Crown Court', 'C06MM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Basildon Crown Court', 'C42BS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Skipton Magistrates'' Court', 'B12LT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wrexham Magistrates'' Court', 'B60OW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Taunton Crown Court', 'C52TA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Stockport Magistrates'' Court', 'B06MK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Nottingham Magistrates'' Court', 'B31JV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bridlington Magistrates'' Court', 'B16CJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Aberystwyth Magistrates'' Court', 'B63AD00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Inner London Crown Court', 'C01IL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Carlisle Crown Court', 'C03CL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Preston Magistrates'' Court', 'B04KO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Blackpool Magistrates'' Court', 'B04BQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Plymouth Crown Court', 'C50PL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Caernarfon Magistrates'' Court', 'B60WU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Cannock Magistrates'' Court', 'B21DA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Stafford Crown Court', 'C21SF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Liverpool Crown Court', 'C05LV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('York Magistrates'' Court', 'B12PA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('St. Albans Magistrates'' Court', 'B41ME00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Stevenage Magistrates'' Court', 'B41MJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Reading Crown Court', 'C43RE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Mold Magistrates'' Court', 'B60JE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Northampton Magistrates'' Court', 'B34JS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Basildon Magistrates'' Court', 'B42AZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bolton Combined Court Centre', 'B06BV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Gloucester Crown Court', 'C53GL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Great Grimsby Crown Court', 'C16GR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Leeds Magistrates'' Court', 'B13HT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Manchester City Magistrates'' Court', 'B06IS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newcastle upon Tyne Crown Court', 'C10NE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Harrow Crown Court', 'C01HA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Warwick Crown Court sitting at Leamington Spa', 'C23WR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Southend-on-Sea Magistrates'' Court', 'B42MB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Huntingdon Magistrates'' Court', 'B35HF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Grimsby Magistrates'' Court', 'B16GB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Haverfordwest Magistrates'' Court', 'B63GN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Huddersfield Magistrates'' Court', 'B13HD00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Herefordshire Magistrates'' Court', 'B22GR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('South Shields Magistrates'' Court', 'B10LX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Luton Crown Court', 'C40LU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Worcester Crown Court', 'C22WC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Ipswich Magistrates'' Court', 'B37HI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newton Aycliffe Magistrates'' Court', 'B11JP00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Stoke-on-Trent Crown Court', 'C21SK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Norwich Magistrates'' Court', 'B36JU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lincoln Magistrates'' Court', 'B32HX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lancaster Crown Court', 'C04LA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Sheffield Magistrates'' Court', 'B14LO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Horsham Magistrates'' Court', 'B47HB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Walsall Magistrates'' Court', 'B20NQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Barnsley Magistrates'' Court', 'B14AV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Leicester Magistrates'' Court', 'B33HU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Great Yarmouth Magistrates'' Court', 'B36FZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Berwick-upon-Tweed Magistrates'' Court', 'B10BF00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Mold Crown Court', 'C07MO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Liverpool Magistrates'' Court', 'B05PK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Burnley Magistrates'' Court', 'B04CO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Medway Magistrates'' Court', 'B46DH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('North Somerset Magistrates'' Court', 'B52OC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Aldershot Magistrates'' Court', 'B44AG00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('King''s Lynn Crown Court', 'C36KL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Teesside Magistrates'' Court', 'B17JA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Isle of Wight Magistrates'' Court', 'B44JK00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Eastbourne Magistrates'' Court', 'B47FB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('North Shields Magistrates'' Court', 'B10JQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Tameside Magistrates'' Court', 'B06AN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Wycombe Magistrates'' Court', 'B43OX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newport Magistrates'' Court (Crown Court Bldg)', 'B61WY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bedford Magistrates'' Court', 'B40BC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chester Magistrates'' Court', 'B07DM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Winchester Combined Court', 'B44WZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Warrington Combined Court', 'B07FQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bournemouth Combined Court', 'B55IS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('West Norfolk Magistrates'' Court', 'B36HN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('South East Northumberland Magistrates'' Court (aka Bedlington MC)', 'B10BD00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Darlington Magistrates'' Court', 'B11EI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bexley Magistrates'' Court', 'B01BH00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Merthyr Tydfil Magistrates'' Court', 'B62IZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Loughborough Magistrates'' Court', 'B33II00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chichester Crown Court', 'C47CC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Chorley Magistrates'' Court', 'B04DS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Gateshead Magistrates'' Court', 'B10FR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Salisbury Magistrates'' Court', 'B54WV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('North Staffordshire Justice Centre', 'B21JI00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Hatfield Magistrates'' Court', 'B41US00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Leamington Spa Magistrates'' Court', 'B23HS00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lancaster Magistrates'' Court', 'B04HQ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Lavender Hill Magistrates'' Court', 'B01LY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Bolton Crown Court', 'C06BO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Kingston-upon-Hull Crown Court', 'C16HU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('South Sefton Magistrates'' Court', 'B05BW00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Sunderland Magistrates'' Court', 'B10MR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Yeovil Magistrates'' Court', 'B52OZ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Newton Abbot Magistrates'' Court', 'B50JO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Brighton Magistrates'' Court', 'B47CL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Margate Magistrates'' Court', 'B46IU00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Southampton Magistrates'' Court', 'B44MA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Portsmouth Magistrates'' Court', 'B44KM00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Basingstoke Magistrates'' Court', 'B44BA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Swindon Crown Court', 'C54SD00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Truro Crown Court', 'C50TR00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Crawley Magistrates'' Court', 'B47EC00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Oxford Magistrates'' Court', 'B43KB00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Aylesbury Crown Court', 'C43AY00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Court of Appeal', 'C01CJ00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Worthing Magistrates'' Court', 'B47OV00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Canterbury Crown Court', 'C46CN00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Portsmouth Crown Court', 'C44PO00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Truro Magistrates'' Court', 'B50NL00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Maidstone Crown Court', 'C46MA00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Merthyr Tydfil Crown Court', 'C62MT00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Weymouth Magistrates'' Court', 'B55OE00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql'),
        ('Oxford Crown Court', 'C43OX00', 0, NOW(), NOW(), false, 'V2122__add_all_crown_court_names.sql')
    ON CONFLICT (COURT_CODE)
    DO
        UPDATE SET name = EXCLUDED.name, version = court.version + 1, created = court.created, last_updated=NOW();