BEGIN;

CREATE TABLE CASE_COMMENTS (
   ID               SERIAL      PRIMARY KEY,
   FK_COURT_CASE_ID INT8        NOT NULL,
   COMMENT_ID       UUID        NOT NULL DEFAULT uuid_generate_v4(),
   COMMENT          TEXT        NOT NULL,
   CREATED          TIMESTAMP   NOT NULL DEFAULT now(),
   CREATED_BY       TEXT        NULL,
   DELETED          BOOLEAN NOT NULL DEFAULT FALSE,
   CONSTRAINT fk_case_comments_court_case FOREIGN KEY (FK_COURT_CASE_ID) REFERENCES COURT_CASE (ID)
);

COMMIT;
