BEGIN;

    ALTER TABLE HEARING_DEFENDANT DROP CONSTRAINT FK_HEARING_DEFENDANT_DEFENDANT;

    DELETE FROM defendant d USING (select id from defendant d2 except SELECT max(id) FROM defendant d2 GROUP BY d2.defendant_id) as to_delete where d.id = to_delete.id;

    UPDATE HEARING_DEFENDANT hdu SET FK_DEFENDANT_ID = d.id FROM DEFENDANT d, HEARING_DEFENDANT hd
    WHERE hd.DEFENDANT_ID = d.DEFENDANT_ID AND hdu.id = hd.id;

    ALTER TABLE HEARING_DEFENDANT ADD CONSTRAINT FK_HEARING_DEFENDANT_DEFENDANT FOREIGN KEY (FK_DEFENDANT_ID) REFERENCES DEFENDANT;

COMMIT