BEGIN;

    ALTER TABLE HEARING_DEFENDANT ADD COLUMN FK_DEFENDANT_ID int8;

    UPDATE HEARING_DEFENDANT hdu SET FK_DEFENDANT_ID = d.id FROM DEFENDANT d, HEARING_DEFENDANT hd
    WHERE hd.DEFENDANT_ID = d.DEFENDANT_ID
        AND hdu.id = hd.id;

    ALTER TABLE HEARING_DEFENDANT ADD CONSTRAINT FK_HEARING_DEFENDANT_DEFENDANT FOREIGN KEY (FK_DEFENDANT_ID) REFERENCES DEFENDANT;

    ALTER TABLE DEFENDANT ADD COLUMN FK_OFFENDER_ID int8;

    UPDATE DEFENDANT du SET FK_OFFENDER_ID = o.id FROM OFFENDER o, DEFENDANT d
    WHERE d.CRN IS NOT NULL
      AND d.CRN = o.CRN
      AND du.id = d.id;

    ALTER TABLE DEFENDANT ADD CONSTRAINT FK_DEFENDANT_OFFENDER FOREIGN KEY (FK_OFFENDER_ID) REFERENCES OFFENDER;

COMMIT