BEGIN

    ALTER TABLE HEARING_DEFENDANT ADD COLUMN FK_DEFENDANT_ID int8;

    UPDATE HEARING_DEFENDANT hdu set hdu.FK_DEFENDANT_ID = d.id from DEFENDANT d, HEARING_DEFENDANT hd
    where hd.DEFENDANT_ID = d.DEFENDANT_ID
        AND hdu.id = hd.id;

    ALTER TABLE DEFENDANT ADD COLUMN FK_OFFENDER_ID int8;

    UPDATE DEFENDANT du set FK_OFFENDER_ID = o.id from OFFENDER o, DEFENDANT d
    WHERE d.CRN is NOT NULL
      AND d.CRN = o.CRN
      AND du.id = d.id;

COMMIT