BEGIN;

ALTER TABLE HEARING_NOTES ADD COLUMN FK_HEARING_DEFENDANT_ID int4;

CREATE INDEX IDX_HEARING_NOTES_FK_HEARING_DEFENDANT_ID on HEARING_NOTES(FK_HEARING_DEFENDANT_ID);

ALTER TABLE HEARING_NOTES ADD CONSTRAINT fk_hearing_note_hearing_defendant FOREIGN KEY (fk_hearing_defendant_id) REFERENCES hearing_defendant(id) ON DELETE CASCADE;

COMMIT;