BEGIN;
    ALTER TABLE IF EXISTS OFFENCE ALTER COLUMN SHORT_TERM_CUSTODY_PREDICTOR_SCORE TYPE NUMERIC(21,19);
    ALTER TABLE IF EXISTS OFFENCE_AUD ALTER COLUMN SHORT_TERM_CUSTODY_PREDICTOR_SCORE TYPE NUMERIC(21,19);
COMMIT;