FROM nginx:1.21.0-alpine

RUN chown -R nginx:nginx /etc/nginx

#COPY /nginx.conf /etc/nginx/
#COPY /replicator.conf.template /etc/nginx/templates/
#COPY /default.conf.template /etc/nginx/templates/

EXPOSE 8080
