#!/bin/bash

SRC_PATTERN="src/"
if git diff --cached --name-only | grep --quiet "$SRC_PATTERN"
then
  echo "👷‍♀️ src/ has changed - running integration tests..."
  ./gradlew clean integrationTest
fi

