TRUNCATE courtcaseservicetest.offender_match_group CASCADE;
TRUNCATE courtcaseservicetest.offender_match CASCADE;
TRUNCATE courtcaseservicetest.offender CASCADE;
TRUNCATE courtcaseservicetest.hearing_day CASCADE;
TRUNCATE courtcaseservicetest.hearing CASCADE;
TRUNCATE courtcaseservicetest.court_case CASCADE;
TRUNCATE courtcaseservicetest.court CASCADE;
