generic-service:
  autoscaling:
    minReplicas: 1
    maxReplicas: 2

  env:
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: dev
    COMMUNITY_API_BASE_URL: https://court-case-and-delius-dev.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    OFFENDER_ASSESSMENTS_API_BASE_URL: "https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"
    DELIUS_BASE_URL: "https://ndelius.test.probation.service.justice.gov.uk"
    PRISON_API_BASE_URL: "https://prison-api-dev.prison.service.justice.gov.uk/"
    MANAGE_OFFENCES_API_BASE_URL: "https://manage-offences-api-dev.hmpps.service.justice.gov.uk"
    COURT_CASE_AND_DELIUS_API_BASE_URL: "https://court-case-and-delius-dev.hmpps.service.justice.gov.uk"
    DOMAIN_EVENT_AND_DELIUS_API_BASE_URL: "https://domain-events-and-delius-dev.hmpps.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_CLIENT_BASE_URL: "https://document-api-dev.hmpps.service.justice.gov.uk"
    HEARING_OUTCOMES_MOVE_UN_RESULTED_TO_OUTCOMES_CUTOFF_TIME: "12:00"
    INGRESS_URL: "court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk"

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 250m
      memory: 350Mi

ingress:
  class: modsec
  hosts:
    - host: court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

nginx_proxy:
  service_host: http://court-case-service.court-probation-dev
  replicaCount: 1

hearing_outcomes:
  process_un_resulted_cases_cron: "30 12-20 * * *"

generic-prometheus-alerts:
  alertSeverity: probation_in_court_alerts_dev

# TODO - data-dictionary nginx fails currently blocking deployment of court-case-service too.
#  Fix this issue and uncomment below entries for data-dictionary to deploy.
#data_dictionary:
#  name: pic-data-dictionary
#  service_host: http://pic-data-dictionary.pic-data-dictionary
#  replicaCount: 1
#
#  service:
#    port:
#      http: 80
#
#  deployment:
#    image:
#      repository: quay.io/hmpps/pic-data-dictionary
#      tag: latest
#      pullPolicy: Always
#    port: 80