# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 1
maxReplicaCount: 2
maxSurge: 1

image:
  repository: quay.io/hmpps/court-case-service
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  service: court-case-service-proxy
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

nginx_proxy:
  name: court-case-service-proxy
  service_host: http://court-case-service.court-probation-dev
  replicaCount: 1

  service:
    port:
      http: 80

  deployment:
    image:
      repository: quay.io/hmpps/court-case-service-nginx
      tag: latest
      pullPolicy: Always
    port: 8080

data_dictionary:
  name: pic-data-dictionary
  service_host: http://pic-data-dictionary.pic-data-dictionary
  replicaCount: 1

  service:
    port:
      http: 80

  deployment:
    image:
      repository: quay.io/hmpps/pic-data-dictionary
      tag: latest
      pullPolicy: Always
    port: 8080

env:
  JAVA_OPTS: "-Xmx512m"
  community_api:
    base_url: https://community-api-secure.test.delius.probation.hmpps.dsd.io
  nomis_oauth:
    base_url: https://sign-in-dev.hmpps.service.justice.gov.uk
  offender_assessments_api:
    base_url: https://offender-dev.aks-dev-1.studio-hosting.service.justice.gov.uk/
  delius:
    base_url: https://ndelius.test.probation.service.justice.gov.uk
  prison_api:
    base_url: https://api-dev.prison.service.justice.gov.uk/

spring:
  profile: instrumented

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

resources:
  cpu:
    limit: 5000m
    request: 250m
  memory:
    limit: 1200Mi
    request: 350Mi

