generic-service:
  autoscaling:
    minReplicas: 2
    maxReplicas: 8

  env:
    JAVA_OPTS: "-Xmx2048m"
    SPRING_PROFILES_ACTIVE: "instrumented"
    COMMUNITY_API_BASE_URL: "https://court-case-and-delius-preprod.hmpps.service.justice.gov.uk"
    NOMIS_OAUTH_BASE_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    OFFENDER_ASSESSMENTS_API_BASE_URL: "https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk"
    DELIUS_BASE_URL: "https://ndelius.stage.probation.service.justice.gov.uk"
    PRISON_API_BASE_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    MANAGE_OFFENCES_API_BASE_URL: "https://manage-offences-api-preprod.hmpps.service.justice.gov.uk"
    COURT_CASE_AND_DELIUS_API_BASE_URL: "https://court-case-and-delius-preprod.hmpps.service.justice.gov.uk"
    DOMAIN_EVENT_AND_DELIUS_API_BASE_URL: "https://domain-events-and-delius-preprod.hmpps.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_CLIENT_BASE_URL: "https://document-api-preprod.hmpps.service.justice.gov.uk"
    HEARING_OUTCOMES_MOVE_UN_RESULTED_TO_OUTCOMES_CUTOFF_TIME: "11:00"
    INGRESS_URL: "court-case-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"

  resources:
    limits:
      cpu: 5000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi

ingress:
  class: modsec-non-prod
  hosts:
    - host: court-case-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk

nginx_proxy:
  service_host: http://court-case-service.court-probation-preprod
  replicaCount: 1

hearing_outcomes:
  process_un_resulted_cases_cron: "30 15-20 * * *"

generic-prometheus-alerts:
  alertSeverity: probation_in_court_alerts_preprod