generic-service:
  autoscaling:
    minReplicas: 2
    maxReplicas: 8

  env:
    JAVA_OPTS: "-Xmx2048m"
    SPRING_PROFILES_ACTIVE: "instrumented"
    COMMUNITY_API_BASE_URL: "https://court-case-and-delius.hmpps.service.justice.gov.uk"
    NOMIS_OAUTH_BASE_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    OFFENDER_ASSESSMENTS_API_BASE_URL: "https://assess-risks-and-needs.hmpps.service.justice.gov.uk"
    DELIUS_BASE_URL: "https://ndelius.probation.service.justice.gov.uk"
    PRISON_API_BASE_URL: "https://prison-api.prison.service.justice.gov.uk"
    MANAGE_OFFENCES_API_BASE_URL: "https://manage-offences-api.hmpps.service.justice.gov.uk"
    COURT_CASE_AND_DELIUS_API_BASE_URL: "https://court-case-and-delius.hmpps.service.justice.gov.uk"
    DOMAIN_EVENT_AND_DELIUS_API_BASE_URL: "https://domain-events-and-delius.hmpps.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_CLIENT_BASE_URL: "https://document-api.hmpps.service.justice.gov.uk"
    HEARING_OUTCOMES_MOVE_UN_RESULTED_TO_OUTCOMES_CUTOFF_TIME: "18:29"
    INGRESS_URL: "court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk"

  resources:
    limits:
      cpu: 5000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi

takeDatabaseSnapshots: true

ingress:
  class: modsec
  hosts:
    - host: court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk
      cert_secret: court-case-service-cert

nginx_proxy:
  service_host: http://court-case-service.court-probation-prod
  replicaCount: 2

analytics_data_extractor:
  resources:
    memory:
      limit: 4Gi
      request: 2Gi

hearing_outcomes:
  process_un_resulted_cases_cron: "0,30 22-23 * * *"

generic-prometheus-alerts:
  alertSeverity: probation_in_court_alerts_prod