# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 1
maxReplicaCount: 2
maxSurge: 1
takeDatabaseSnapshots: false

image:
  repository: quay.io/hmpps/court-case-service
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  service: court-case-service-proxy
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

nginx_proxy:
  name: court-case-service-proxy
  service_host: http://court-case-service.court-probation-dev
  replicaCount: 1

  service:
    port:
      http: 80

  deployment:
    image:
      repository: quay.io/hmpps/court-case-service-nginx
      tag: latest
      pullPolicy: Always
    port: 8080

# TODO - data-dictionary nginx fails currently blocking deployment of court-case-service too.
#  Fix this issue and uncomment below entries for data-dictionary to deploy.
#data_dictionary:
#  name: pic-data-dictionary
#  service_host: http://pic-data-dictionary.pic-data-dictionary
#  replicaCount: 1
#
#  service:
#    port:
#      http: 80
#
#  deployment:
#    image:
#      repository: quay.io/hmpps/pic-data-dictionary
#      tag: latest
#      pullPolicy: Always
#    port: 80

hearing_outcomes:
  process_un_resulted_cases_cron: "30 12-20 * * *"

env:
  JAVA_OPTS: "-Xmx512m"
  FEATURE_FLAGS_ENABLE_CACHEABLE_CASE_LIST: false
  community_api:
    base_url: https://community-api-secure.test.delius.probation.hmpps.dsd.io
  nomis_oauth:
    base_url: https://sign-in-dev.hmpps.service.justice.gov.uk
  offender_assessments_api:
    base_url: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
  delius:
    base_url: https://ndelius.test.probation.service.justice.gov.uk
  prison_api:
    base_url: https://prison-api-dev.prison.service.justice.gov.uk/
  manage_offences_api:
    base_url: https://manage-offences-api-dev.hmpps.service.justice.gov.uk
  court_case_and_delius_api:
    base_url: https://court-case-and-delius-dev.hmpps.service.justice.gov.uk
  domain_event_and_delius_api:
    base_url: https://domain-events-and-delius-dev.hmpps.service.justice.gov.uk
  hearing_outcomes:
    move_un_resulted_to_outcomes_cutoff_time: "12:00"
    move_un_resulted_to_outcomes_courts: "B20EB,B23HS"
  hmpps_document_management_api_client:
    base_url: https://document-api-dev.hmpps.service.justice.gov.uk

spring:
  profile: dev

resources:
  cpu:
    limit: 5000m
    request: 250m
  memory:
    limit: 1200Mi
    request: 350Mi

alertSeverity: probation_in_court_alerts_dev